"""initial_schema_all_28_models

Revision ID: b7d14d039c02
Revises: 
Create Date: 2026-07-31 18:18:21.338533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7d14d039c02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('email_domain', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.Text(), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('onboarded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('academic_years',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('year_label', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('roll_number', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('profile_pic_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('year_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('program', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['year_id'], ['academic_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concept_mastery',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('concept', sa.Text(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=True),
    sa.Column('experiment_count', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'concept')
    )
    op.create_table('environment_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('docker_image', sa.Text(), nullable=False),
    sa.Column('is_platform_default', sa.Boolean(), nullable=True),
    sa.Column('pip_packages', sa.JSON(), nullable=True),
    sa.Column('apt_packages', sa.JSON(), nullable=True),
    sa.Column('build_status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('env_profile_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['env_profile_id'], ['environment_profiles.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('instructor_id', sa.String(length=36), nullable=False),
    sa.Column('exp_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('aim', sa.Text(), nullable=True),
    sa.Column('theory', sa.Text(), nullable=True),
    sa.Column('problem_statement', sa.Text(), nullable=True),
    sa.Column('input_format', sa.Text(), nullable=True),
    sa.Column('output_format', sa.Text(), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('concept_tags', sa.JSON(), nullable=True),
    sa.Column('allowed_languages', sa.JSON(), nullable=True),
    sa.Column('is_multi_file', sa.Boolean(), nullable=True),
    sa.Column('file_structure', sa.JSON(), nullable=True),
    sa.Column('rubric_test_cases', sa.Integer(), nullable=True),
    sa.Column('rubric_lab_report', sa.Integer(), nullable=True),
    sa.Column('rubric_code_quality', sa.Integer(), nullable=True),
    sa.Column('rubric_viva', sa.Integer(), nullable=True),
    sa.Column('enable_viva', sa.Boolean(), nullable=True),
    sa.Column('enable_lockdown', sa.Boolean(), nullable=True),
    sa.Column('time_limit_sec', sa.Integer(), nullable=True),
    sa.Column('memory_limit_kb', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section_students',
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('section_id', 'student_id')
    )
    op.create_table('section_subjects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('instructor_id', sa.String(length=36), nullable=False),
    sa.Column('co_instructor_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['co_instructor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_modules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('module_type', sa.String(length=10), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content_data', sa.JSON(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('min_watch_pct', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('section_subject_id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('gate_score_threshold', sa.Integer(), nullable=True),
    sa.Column('late_join_window_min', sa.Integer(), nullable=True),
    sa.Column('catchup_enabled', sa.Boolean(), nullable=True),
    sa.Column('catchup_deadline', sa.DateTime(), nullable=True),
    sa.Column('focus_ml_enabled', sa.Boolean(), nullable=True),
    sa.Column('lockdown_enabled', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('jitsi_room_name', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['section_subject_id'], ['section_subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_rankings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('section_subject_id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('effort_score', sa.Float(), nullable=True),
    sa.Column('efficiency_score', sa.Float(), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.Column('rank_score', sa.Float(), nullable=True),
    sa.Column('rank_position', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['section_subject_id'], ['section_subjects.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'section_subject_id', name='uq_student_section_subject')
    )
    op.create_table('test_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=True),
    sa.Column('expected_output', sa.Text(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('points_weight', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('files', sa.JSON(), nullable=False),
    sa.Column('stdin', sa.Text(), nullable=True),
    sa.Column('compile_status', sa.String(length=20), nullable=True),
    sa.Column('compile_output', sa.Text(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('test_cases_passed', sa.Integer(), nullable=True),
    sa.Column('test_cases_total', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('memory_used_kb', sa.Integer(), nullable=True),
    sa.Column('loc', sa.Integer(), nullable=True),
    sa.Column('cyclomatic_complexity', sa.Float(), nullable=True),
    sa.Column('quality_grade', sa.String(length=2), nullable=True),
    sa.Column('is_final_submission', sa.Boolean(), nullable=True),
    sa.Column('is_catchup', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['lab_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('files', sa.JSON(), nullable=False),
    sa.Column('is_full_snapshot', sa.Boolean(), nullable=True),
    sa.Column('diff_from_prev', sa.Text(), nullable=True),
    sa.Column('saved_at', sa.DateTime(), nullable=True),
    sa.Column('save_type', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['lab_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_progress',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('module_id', sa.String(length=36), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('watch_pct', sa.Float(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['content_modules.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'module_id')
    )
    op.create_table('focus_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('tab_switches', sa.Integer(), nullable=True),
    sa.Column('window_blurs', sa.Integer(), nullable=True),
    sa.Column('idle_seconds', sa.Integer(), nullable=True),
    sa.Column('copy_paste_count', sa.Integer(), nullable=True),
    sa.Column('face_present_pct', sa.Float(), nullable=True),
    sa.Column('gaze_score', sa.Float(), nullable=True),
    sa.Column('large_paste_detected', sa.Boolean(), nullable=True),
    sa.Column('typing_speed_avg', sa.Float(), nullable=True),
    sa.Column('focus_score', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['lab_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('auto_grade', sa.Float(), nullable=True),
    sa.Column('manual_grade', sa.Float(), nullable=True),
    sa.Column('manual_feedback', sa.Text(), nullable=True),
    sa.Column('viva_grade', sa.Float(), nullable=True),
    sa.Column('hint_deduction', sa.Float(), nullable=True),
    sa.Column('final_grade', sa.Float(), nullable=True),
    sa.Column('code_quality_grade', sa.Float(), nullable=True),
    sa.Column('graded_by', sa.String(length=36), nullable=True),
    sa.Column('graded_at', sa.DateTime(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['graded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['lab_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hint_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('hint_level', sa.Integer(), nullable=False),
    sa.Column('prompt_sent', sa.Text(), nullable=True),
    sa.Column('response_received', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('is_fallback', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['lab_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plagiarism_flags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('student_a_id', sa.String(length=36), nullable=False),
    sa.Column('student_b_id', sa.String(length=36), nullable=False),
    sa.Column('similarity_pct', sa.Float(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['lab_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_a_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_b_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('module_id', sa.String(length=36), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.String(length=5), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['content_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_attendance',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('reconnect_count', sa.Integer(), nullable=True),
    sa.Column('total_time_seconds', sa.Integer(), nullable=True),
    sa.Column('is_catchup', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=True),
    sa.Column('is_active_participant', sa.Boolean(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('override_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['override_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['lab_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'student_id')
    )
    op.create_table('session_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('experiment_clarity', sa.Integer(), nullable=True),
    sa.Column('session_pacing', sa.Integer(), nullable=True),
    sa.Column('ai_hint_helpfulness', sa.Integer(), nullable=True),
    sa.Column('overall_rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['lab_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inline_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grade_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('viva_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('grade_id', sa.String(length=36), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('viva_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('viva_session_id', sa.String(length=36), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['viva_session_id'], ['viva_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viva_answers')
    op.drop_table('viva_sessions')
    op.drop_table('inline_comments')
    op.drop_table('session_feedback')
    op.drop_table('session_attendance')
    op.drop_table('quiz_questions')
    op.drop_table('plagiarism_flags')
    op.drop_table('hint_logs')
    op.drop_table('grades')
    op.drop_table('focus_scores')
    op.drop_table('content_progress')
    op.drop_table('code_versions')
    op.drop_table('code_attempts')
    op.drop_table('test_cases')
    op.drop_table('student_rankings')
    op.drop_table('lab_sessions')
    op.drop_table('content_modules')
    op.drop_table('section_subjects')
    op.drop_table('section_students')
    op.drop_table('experiments')
    op.drop_table('subjects')
    op.drop_table('sections')
    op.drop_table('notifications')
    op.drop_table('environment_profiles')
    op.drop_table('concept_mastery')
    op.drop_table('batches')
    op.drop_table('users')
    op.drop_table('academic_years')
    op.drop_table('institutions')
    # ### end Alembic commands ###
